### ISSUE TITLE
O365 Need admin approval

### ISSUE THREAD

**Issue by Edward-Adamson** [johnnliu/Flow-Studio-Issues#171]
Hi,

I'm wanting to try out flow studio recently we have been using lots more flows and they are incredibly hard to sort using the out of the box flow site.

Though my IT department can't seem to see where to give access to my account.

When I log in I get a need admin approval message, which doesn't tell us which feature we should be turning on.

![image](https://user-images.githubusercontent.com/32546798/84639447-4c143c00-aef0-11ea-88fb-4dc5068fd279.png)

I understand this isn't an issue with the product but any guidance would be appreciated :)

**Comment by johnnliu** [comment]
Hi, Flow Studio App needs a very broad low level permission, this is usually something that doesn't require IT admin approval, but some tenants have made it require.  The permission we ask for here is:

https://management.azure.com/user_impersonation

Because Microsoft Flows and Power Apps are built on top of the Azure platform - the easiest permission that will allow us to do all the scanning is being able to read Azure as you.  Flow Studio stores this token in your browser and conversations between you, Flow Studio and the Power Platform is entirely within your browser to Microsoft.

I do track page view usage (to troubleshoot if people get stuck or there's an unknown error on some page), but I don't capture your tokens.

(Technically, because we can talk to Azure - Flow Studio is actually able to read and monitor Logic Apps as well, we just haven't had any request to build this)

Let me know if this is enough, or does your IT has any specific questions.

**Comment by Edward-Adamson** [comment]
Thanks, unfortunately our IT isn't well versed in the Azure ecosystem and the only thing they use heavily active directory. We seem to be able to use basic Flow and PowerApps without any involvement from IT.

This is still something I will still be following this up as it looks like flow studio will help a lot for me trying to administer different flows. But its likely this will take me weeks rather than days at my end :(

**Comment by Edward-Adamson** [comment]
I have managed to get access to the app now 😁 Now I need to get Flow admin access which I think requires a Flow premium subscription, i'm currently on a E3 license. Then I can look at some of the extended features of this app too!
